name: Setup Java and Cache Scala deps with sbt
description: Setup Java and cache Scala deps with sbt
inputs:
  cache-build-deps-ver:
    description: The version of build dependencies cache.
    required: true
  cache-build-outputs-ver:
    description: The version of build outputs cache.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17
    - name: Prepare build dependencies cache
      uses: actions/cache@v4
      env:
        cache-name: cache-build-dependencies
        cache-version: ${{ inputs.cache-build-deps-ver }}
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.m2
          ~/.cache
        key: build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-
          build-${{ env.cache-name }}-${{ env.cache-version }}-
    - name: Prepare build cache
      if: github.ref != 'refs/heads/main'
      uses: actions/cache@v4
      env:
        cache-name: cache-build
        cache-version: ${{ inputs.cache-build-outputs-ver }}
      with:
        path: |
          target
          project/target
          project/project/target
        key: build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-
          build-${{ env.cache-name }}-${{ env.cache-version }}-
