name: CD
on:
  workflow_call:
jobs:
  output-sha:
    name: Get SHA value of the latest commit
    runs-on: ubuntu-24.04
    outputs:
      tag-name: ${{ steps.tag-name.outputs.tag-name }}
    steps:
      - uses: actions/checkout@v4
      - name: Outputs the value
        id: output-sha
        run: |
          VALUE=$(git log --format='%h' -n 1)
          echo "sha=$VALUE" >> $GITHUB_OUTPUT
          echo $VALUE
        shell: bash
      - name: Create and push a tag
        id: tag-name
        run: |
          TAG_NAME=sha-${{ steps.output-sha.outputs.sha }}
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "tag-name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo $TAG_NAME
  cd:
    name: Create release
    runs-on: ubuntu-24.04
    needs:
      - output-sha
    # softprops/action-gh-release requires this permisson
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: Rename jar
        working-directory: ./artifact/
        run: |
          for file in $(find . -type f -name '*.jar'); do
            baseFileName=$(basename "$file" '.jar')
            mv "$file" "$baseFileName-$TAG_NAME.jar"
          done
        env:
          TAG_NAME: ${{ needs.tag-name.outputs.tag-name }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.tag-name.outputs.tag-name }}
          draft: false
          prerelease: true
          files: artifact/*.jar
