# Reusable workflowが内部のActionを使う際のフォーマットにactionlintが対応していないので、単なるymlのlintだけする
name: Run yamllint
on:
  push:
    branches:
      - main
    paths:
      - ".github/**/*.yml"
  pull_request:
    paths:
      - ".github/**/*.yml"
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
