name: reviewdog
on:
  push:
    branches:
      - main
    paths:
      - ".github/**/*.yml"
  pull_request:
    paths:
      - ".github/**/*.yml"
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - name: Run actionlint
        run: actionlint
