name: CD
on:
  workflow_call:
    inputs:
      cache-build-deps-ver:
        type: string
        required: true
      cache-build-outputs-ver:
        type: string
        required: true
      jar-output-dir:
        type: string
        required: true
jobs:
  cd:
    name: Release
    runs-on: ubuntu-latest
    # softprops/action-gh-release requires this permisson
    permissions:
      contents: write
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          repository: Lucky3028/shared-workflows
          ref: main
          path: .github/actions/shared-workflows
      - name: Setup Java and Cache deps
        uses: ./.github/actions/shared-workflows/.github/actions/setup-scala-sbt-build
        with:
          cache-build-deps-ver: ${{ inputs.cache-build-deps-ver }}
          cache-build-outputs-ver: ${{ inputs.cache-build-outputs-ver }}

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v4.0.0
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: github-actions[bot]
          git-user-email: github-actions[bot]@users.noreply.github.com
          skip-version-file: 'true'
          skip-git-pull: 'true'
      # バージョンが異なっているので、ここでBuild
      - name: Build artifact
        run: sbt assembly
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          files: ./target/${{ inputs.jar-output-dir }}/*.jar

      - name: Clean build artifact for caching target folder
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: rm -r target/${{ inputs.jar-output-dir }}
